### PR TITLE
Handle Rails 5 #tables deprecation

### PR DESCRIPTION
**Pull request by xinranxiao**
Similar to #57 , but keeps support for Rails < 5.0.

Added ActiveRecord 5 to the travis build... some tests are failing will check them out tomorrow.

### CODE REVIEW

**Comment by pboling** [comment]
Oh wonderful!  This is exactly what I was planning to do, and then after we get Rails 5 support done, we can deprecate the old rails and remove switches.  Thanks!  Some of the tests fail randomly on Travis, I think.

**Comment by xinranxiao** [comment]
Yeah I think the jruby ones are pretty screwed up, I'll remove the AR5-jruby-9.0.1.0 case

**Comment by xinranxiao** [comment]
@pboling Hi, any chance on merging this soon?

**Comment by pboling** [comment]
Yes!  Merging.

**Comment by xinranxiao** [comment]
Any chance on bumping the version for this? :)

**Comment by xinranxiao** [comment]
bump @pboling

**Comment by pboling** [comment]
I will bump the version and release.  I just need to fix the test suite.  I will get to it very soon.

**Comment by xinranxiao** [comment]
awesome thanks!

**Pull request merged**
